export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#050810] text-white p-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-6 text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-fuchsia-500">
          Terms of Service
        </h1>
        
        <div className="space-y-6 text-slate-300">
          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">1. Service Description & AI Origin</h2>
            <p className="mb-3">
              Multiverse Mouse provides an interface for AI-powered image generation. Our "Nano Banana Pro" engine is powered by the <strong className="text-white">Google Gemini API</strong>. By using this service, you acknowledge that outputs are generated by artificial intelligence and may contain an invisible digital watermark (SynthID) to identify their AI origin.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">2. Eligibility</h2>
            <p className="font-bold text-yellow-400">
              You must be at least 18 years of age to purchase tickets or generate images on Multiverse Mouse. Our service is not directed at or intended for individuals under the age of 18.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">3. Ticket Purchases & Credits</h2>
            <div className="space-y-3">
              <div>
                <h3 className="font-bold text-white mb-1">Non-Refundable</h3>
                <p>All ticket purchases are final and non-refundable once the transaction is completed via PayPal.</p>
              </div>
              <div>
                <h3 className="font-bold text-white mb-1">Usage</h3>
                <p>One (1) ticket allows for one (1) high-fidelity image generation.</p>
              </div>
              <div>
                <h3 className="font-bold text-white mb-1">Expiration</h3>
                <p>Tickets currently do not expire, but we reserve the right to modify this policy with 30 days' notice.</p>
              </div>
            </div>
          </section>

          <section className="border-2 border-red-500/30 bg-red-500/5 p-4 rounded-lg">
            <h2 className="text-2xl font-bold text-red-400 mb-3">4. Prohibited Use Policy</h2>
            <p className="mb-3 font-bold">Users are strictly prohibited from using our AI tools to generate:</p>
            <ul className="list-disc ml-6 space-y-2">
              <li><strong>Non-consensual sexual content</strong> or deepfakes of real people</li>
              <li><strong>Hate speech, harassment,</strong> or content depicting self-harm or violence</li>
              <li><strong>Copyrighted characters or trademarks</strong> that the user does not have the legal right to use</li>
              <li><strong>Medical advice</strong> or clinical diagnostic imagery</li>
            </ul>
            <p className="mt-3 font-bold text-red-400">
              ⚠️ Violation of these rules will result in an immediate permanent ban without a refund.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">5. Ownership & Copyright</h2>
            <div className="space-y-3">
              <div>
                <h3 className="font-bold text-white mb-1">User Ownership</h3>
                <p>We claim no ownership over the images you generate. You own the specific output created by your prompts.</p>
              </div>
              <div>
                <h3 className="font-bold text-white mb-1">AI Disclosure</h3>
                <p>While you own the image, current laws (as of 2026) may limit your ability to copyright fully automated AI outputs without significant human modification.</p>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">6. Image Storage & Deletion</h2>
            <ul className="list-disc ml-6 space-y-2">
              <li>Images are temporarily stored for <strong className="text-white">30 days</strong> on our secure servers (Vercel/Google Cloud)</li>
              <li>Users are <strong className="text-white">solely responsible</strong> for downloading their images</li>
              <li>Data is <strong className="text-white">permanently deleted</strong> after 30 days to protect your privacy and optimize our storage costs</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">7. Contact & Support</h2>
            <p>For questions about these terms, contact us at <a href="mailto:DirtySecretAi@gmail.com" className="text-cyan-400 hover:underline">DirtySecretAi@gmail.com</a></p>
          </section>
        </div>

        <div className="mt-12 text-center border-t border-slate-800 pt-6">
          <p className="text-sm text-slate-500">Last updated: January 20, 2026</p>
        </div>
      </div>
    </div>
  )
}

