import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | AI Design Studio',
  description: 'Terms of Service for AI Design Studio AI image generation platform',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-900 via-slate-800 to-slate-900 text-slate-100">
      <div className="max-w-4xl mx-auto px-6 py-12">
        <h1 className="text-4xl font-bold mb-2 text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-purple-400">
          Terms of Service
        </h1>
        <p className="text-slate-400 mb-8">Last Updated: February 27, 2026 | Version 4.0</p>

        <div className="space-y-8 text-slate-300">
          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">1. Acceptance of Terms</h2>
            <p className="mb-4">
              By accessing or using AI Design Studio ("the Service"), operated by Prompt & Protocol LLC, you agree to be bound by these Terms of Service ("Terms").
              If you do not agree to these Terms, do not use the Service.
            </p>
            <p className="mb-4 font-bold text-yellow-400">
              You must be at least 18 years of age to use this Service. Our service is not directed at or intended for individuals
              under the age of 18. By using the Service, you represent and warrant that you are at least 18 years old.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">2. Service Description</h2>
            <p className="mb-4">
              AI Design Studio provides AI-powered image generation services using third-party artificial intelligence models and APIs.
              Our service currently offers multiple AI models accessed through:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>Image Generation</strong> — AI-powered image models via fal.ai and Google Gemini API:</li>
              <ul className="list-disc list-inside space-y-1 ml-8">
                <li>NanoBanana Cluster (Google Gemini 2.5 Flash) — 2 images per use</li>
                <li>NanoBanana Pro (Google Gemini 3 Pro) — Premium quality image generation</li>
                <li>SeeDream 4.5 (ByteDance) — High-quality image generation</li>
                <li>FLUX 2 (Black Forest Labs) — Photorealistic image generation</li>
                <li>Pro Scanner v3 (Google Gemini 3 Pro) — Direct API, no filtering</li>
                <li>Flash Scanner v2.5 (Google Gemini 2.5 Flash) — Fast direct API generation</li>
              </ul>
              <li><strong>Video Generation</strong> — AI-powered video models via fal.ai:</li>
              <ul className="list-disc list-inside space-y-1 ml-8">
                <li>Kling 3.0 (Kuaishou) — Text-to-video generation with optional audio, 3–15 seconds</li>
              </ul>
              <li><strong>AI Design Studio Tools</strong> — Advanced canvas-based creative tools:</li>
              <ul className="list-disc list-inside space-y-1 ml-8">
                <li>Canvas Scanner — Infinite pan/zoom canvas with concurrent multi-image generation</li>
                <li>Composition Canvas — Multi-layer AI composition with inpainting and 4K export</li>
                <li>Scanner Canvas — AI drawing and painting canvas with brush-based generation</li>
              </ul>
            </ul>
            <p className="mt-4 font-semibold text-yellow-400">
              IMPORTANT: The Service includes experimental AI technology that may sometimes provide inaccurate, inappropriate, or
              offensive content. Generated images and suggestions should never be relied upon as professional advice for medical, legal,
              financial, or safety-critical purposes.
            </p>
            <p className="mt-4">By using this Service, you acknowledge that:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>All outputs are generated by artificial intelligence and may be imperfect or unexpected</li>
              <li>Images may contain invisible digital watermarks or metadata identifying their AI origin</li>
              <li>Model availability and pricing are subject to change</li>
              <li>AI models have inherent limitations and biases</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">3. Third-Party Services & Compliance</h2>
            <p className="mb-4">
              Our Service utilizes third-party AI providers. By using our Service, you acknowledge and agree that:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Your use of the Service is also subject to the terms and policies of these third-party providers</li>
              <li>We do not control these third-party services and are not responsible for their availability, functionality, or content</li>
              <li>These providers may have their own data collection and usage policies</li>
              <li>Service availability may be affected by third-party service interruptions or limitations</li>
              <li>We may share your prompts and generated content with these providers as necessary to provide the Service</li>
            </ul>
            <p className="mt-4">You can review the terms of our third-party providers:</p>
            <ul className="list-disc list-inside space-y-2 ml-4 mt-2">
              <li><a href="https://fal.ai/terms" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">fal.ai Terms of Service</a></li>
              <li><a href="https://ai.google.dev/gemini-api/terms" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">Google Gemini API Terms of Service</a></li>
              <li><a href="https://fal.ai/privacy" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">fal.ai Privacy Policy</a></li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">4. User Account and Access</h2>
            <p className="mb-4">To access the Service, you must create an account using Clerk authentication. You are responsible for:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Maintaining the confidentiality of your account credentials</li>
              <li>All activities that occur under your account</li>
              <li>Notifying us immediately of any unauthorized use of your account</li>
              <li>Ensuring your account information is accurate and current</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">5. Tickets and Subscriptions</h2>

            <h3 className="text-xl font-semibold mb-3 text-purple-400">5.1 Ticket System</h3>
            <p className="mb-4">
              The Service operates on a ticket-based system. Each image generation request consumes tickets based on the model and
              settings used:
            </p>
            <ul className="list-disc list-inside space-y-1 ml-4 text-sm">
              <li><strong>Image Models:</strong></li>
              <ul className="list-disc list-inside space-y-1 ml-8">
                <li><strong>NanoBanana Cluster:</strong> 2 tickets (generates 2 images)</li>
                <li><strong>NanoBanana Pro (2K):</strong> 5 tickets per generation</li>
                <li><strong>NanoBanana Pro (4K):</strong> 10 tickets per generation</li>
                <li><strong>SeeDream 4.5 (2K/4K):</strong> 2 tickets per generation</li>
                <li><strong>FLUX 2:</strong> 1 ticket per generation</li>
                <li><strong>Pro Scanner v3 (2K):</strong> 5 tickets per generation</li>
                <li><strong>Pro Scanner v3 (4K):</strong> 10 tickets per generation</li>
                <li><strong>Flash Scanner v2.5:</strong> 1 ticket per generation</li>
              </ul>
              <li><strong>Video Models (Kling 3.0):</strong> Tickets charged per second of video duration</li>
              <ul className="list-disc list-inside space-y-1 ml-8">
                <li>Without audio: 6 tickets per second (e.g., 5s = 30 tickets, 10s = 60 tickets)</li>
                <li>With audio: 8 tickets per second (e.g., 5s = 40 tickets, 10s = 80 tickets)</li>
                <li>Duration options: 3–15 seconds in 1-second increments</li>
              </ul>
            </ul>
            <p className="mt-2 text-sm text-yellow-400">Pricing is subject to change. Ticket costs are deducted at the time of generation and are non-refundable once consumed.</p>

            <h3 className="text-xl font-semibold mb-3 mt-6 text-purple-400">5.2 Dev Tier Subscriptions</h3>
            <p className="mb-4">We offer recurring subscription plans ("Dev Tier") with billing through PayPal:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>Biweekly Plan:</strong> $20 USD every 2 weeks - 250 tickets per cycle</li>
              <li><strong>Monthly Plan:</strong> $40 USD per month - 500 tickets per cycle</li>
              <li><strong>Yearly Plan:</strong> $480 USD per year - 500 tickets per month (6,000 tickets annually)</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3 mt-6 text-purple-400">5.3 Subscription Terms</h3>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Subscriptions automatically renew unless canceled before the next billing cycle</li>
              <li>Tickets are allocated at the start of each billing cycle</li>
              <li>Unused tickets do not roll over to the next billing cycle</li>
              <li>You may cancel your subscription at any time through your account settings</li>
              <li>Cancellation takes effect at the end of the current billing period</li>
              <li><strong>No refunds are provided for partial billing periods or unused tickets</strong></li>
              <li>We reserve the right to modify subscription pricing with 30 days advance notice</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3 mt-6 text-purple-400">5.4 Payment Processing</h3>
            <p className="mb-4">
              All payments are processed through <strong>Lemon Squeezy</strong>, which acts as our Merchant of Record. This means Lemon Squeezy
              is the seller of record for all transactions, handles tax compliance and remittance, and manages payment processing
              on our behalf. By making a purchase, you agree to{' '}
              <a href="https://www.lemonsqueezy.com/terms" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">Lemon Squeezy's Terms of Service</a>{' '}
              and{' '}
              <a href="https://www.lemonsqueezy.com/privacy" target="_blank" rel="noopener noreferrer" className="text-cyan-400 hover:underline">Privacy Policy</a>.
              We are not responsible for any issues arising from Lemon Squeezy's payment processing services, including but not limited to
              payment failures, security breaches, or unauthorized transactions.
            </p>

            <h3 className="text-xl font-semibold mb-3 mt-6 text-purple-400">5.5 One-Time Ticket Purchases</h3>
            <p className="mb-4">
              All one-time ticket purchases are <strong>final and non-refundable</strong> once the transaction is completed. This includes:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Unsuccessful generations due to prohibited content or safety filters</li>
              <li>User dissatisfaction with AI-generated results</li>
              <li>Technical issues with third-party AI providers</li>
              <li>Account suspension or termination for violations</li>
            </ul>
            <p className="mt-4">
              Tickets currently do not expire, but we reserve the right to modify this policy with 30 days' written notice.
            </p>
          </section>

          <section className="border-2 border-red-500/30 bg-red-500/5 p-6 rounded-lg">
            <h2 className="text-2xl font-bold mb-4 text-red-400">6. Prohibited Use Policy</h2>
            <p className="mb-4 font-bold">You agree NOT to use the Service to generate or create:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>Child sexual abuse material (CSAM)</strong> - Any content depicting, sexualizing, or endangering minors</li>
              <li><strong>Non-consensual intimate imagery</strong> - Deepfakes or intimate images of real people without consent</li>
              <li><strong>Hate speech or harassment</strong> - Content targeting individuals based on protected characteristics</li>
              <li><strong>Violence or dangerous activities</strong> - Graphic violence, self-harm, or instructions for illegal activities</li>
              <li><strong>Intellectual property infringement</strong> - Copyrighted characters, trademarks, or logos without authorization</li>
              <li><strong>Fraud or impersonation</strong> - Fake documents, misleading medical/legal content, or identity theft</li>
              <li><strong>Illegal content</strong> - Any content that violates applicable laws or regulations</li>
              <li><strong>Spam or malware</strong> - Mass-generated content or malicious code</li>
            </ul>
            <p className="mt-4">Additionally, you agree NOT to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Reverse engineer, extract, or attempt to recreate the underlying AI models</li>
              <li>Bypass or attempt to bypass content filtering or safety features</li>
              <li>Use the Service for safety-critical applications (medical devices, autonomous vehicles, etc.)</li>
              <li>Use the Service to develop competing AI models or services</li>
              <li>Submit sensitive personal information, confidential data, or protected health information</li>
              <li>Violate the acceptable use policies of our third-party AI providers</li>
            </ul>
            <p className="mt-4 font-bold text-red-400 text-lg">
              ⚠️ Violation of this Prohibited Use Policy will result in immediate permanent account termination without refund of
              remaining tickets or subscription fees.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">7. Content and Intellectual Property</h2>

            <h3 className="text-xl font-semibold mb-3 text-purple-400">7.1 Your Content</h3>
            <p className="mb-4">
              You retain ownership of the text prompts and inputs ("Your Content") that you submit to the Service. By submitting
              Your Content, you grant us a worldwide, non-exclusive, royalty-free license to:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Use, process, and transmit Your Content to provide the Service</li>
              <li>Share Your Content with our third-party AI providers (fal.ai, Google Gemini) for processing</li>
              <li>Use anonymized prompts and usage data to improve our service (no images shared without consent)</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3 mt-6 text-purple-400">7.2 Generated Content</h3>
            <p className="mb-4">
              Subject to your compliance with these Terms and payment of applicable fees, you may use the generated images
              ("Generated Content") for your personal or commercial purposes. However, you acknowledge that:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>We and our AI providers may generate similar or identical content for other users</li>
              <li>We do not guarantee the uniqueness or originality of Generated Content</li>
              <li>AI-generated images may have limited copyright protection under current law</li>
              <li>Fully automated AI outputs may not qualify for copyright without significant human modification</li>
              <li>You are solely responsible for ensuring Generated Content does not infringe third-party rights</li>
              <li>You must comply with all applicable laws when using Generated Content</li>
              <li>Certain AI models may have restrictions on commercial use - you are responsible for compliance</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3 mt-6 text-purple-400">7.3 Image Storage & Deletion</h3>
            <div className="bg-yellow-500/10 border border-yellow-500/30 p-4 rounded-lg mb-3">
              <p className="font-bold text-yellow-400 mb-2">⚠️ IMPORTANT: Download Responsibility</p>
              <p>You are <strong>solely responsible</strong> for downloading and backing up your generated images. We provide temporary storage only.</p>
            </div>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Images are stored for <strong>30 days maximum</strong> on secure cloud servers (Vercel Blob Storage)</li>
              <li>After 30 days, images are <strong>permanently and automatically deleted</strong></li>
              <li>We do not offer image recovery services after deletion</li>
              <li>Storage duration may be reduced with notice during periods of high storage costs</li>
            </ul>

            <h3 className="text-xl font-semibold mb-3 mt-6 text-purple-400">7.4 Service Content</h3>
            <p className="mb-4">
              The Service, including its design, code, features, and functionality, is owned by Prompt & Protocol LLC and is protected
              by copyright, trademark, and other intellectual property laws. You may not copy, modify, distribute, or create
              derivative works based on the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">8. Data Usage and Privacy</h2>
            <p className="mb-4">
              Your use of the Service is subject to our Privacy Policy. Please review our <a href="/privacy" className="text-cyan-400 hover:underline">Privacy Policy</a> to understand how we collect, use, and protect your information.
            </p>
            <p className="mb-4 font-semibold text-yellow-400">
              IMPORTANT DATA SHARING NOTICE:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li><strong>fal.ai:</strong> When using models through fal.ai, your prompts and generated content may be used by fal.ai to improve their services, subject to fal.ai's terms</li>
              <li><strong>Google Gemini (Unpaid Services):</strong> When using unpaid Gemini services, Google uses submitted content and generated responses to improve their products and machine learning technologies</li>
              <li><strong>Google Gemini (Paid Services):</strong> When using paid Gemini services, Google does not use prompts/responses for improvement but logs them for 30 days for violation detection</li>
              <li><strong>Do not submit sensitive, confidential, or personal information to the Service</strong></li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">9. Service Availability and Modifications</h2>
            <p className="mb-4">We reserve the right to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Modify, suspend, or discontinue any aspect of the Service at any time</li>
              <li>Change pricing, features, or ticket allocation with reasonable notice (30 days for material changes)</li>
              <li>Impose usage limits or rate limits on the Service to prevent abuse</li>
              <li>Update these Terms at any time by posting revised Terms on the Service</li>
            </ul>
            <p className="mt-4">
              The Service is provided "as available" and may experience downtime due to maintenance, third-party service issues
              (fal.ai, Google Gemini), or other factors beyond our control. We do not guarantee uninterrupted service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">10. Geographic Restrictions</h2>
            <p className="mb-4">
              The Service may not be available in all geographic regions. Due to third-party AI provider restrictions (specifically
              Google Gemini API requirements), users in the European Economic Area (EEA), Switzerland, and United Kingdom may be
              required to use paid services only. We reserve the right to limit Service availability based on geographic location.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">11. Disclaimer of Warranties</h2>
            <div className="bg-slate-800/50 border-2 border-slate-700 p-4 rounded-lg">
              <p className="mb-3 font-bold text-white uppercase">
                THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
                INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT,
                OR ACCURACY.
              </p>
              <p className="mb-3">We specifically disclaim any warranties regarding:</p>
              <ul className="list-disc list-inside space-y-2 ml-4 text-sm">
                <li>The accuracy, quality, appropriateness, or suitability of Generated Content for any purpose</li>
                <li>Uninterrupted or error-free operation of the Service</li>
                <li>The security or privacy of data transmitted through the Service</li>
                <li>The availability or performance of third-party AI providers (fal.ai, Google Gemini)</li>
                <li>The uniqueness or non-infringement of Generated Content</li>
                <li>The results you may obtain from using the Service</li>
              </ul>
              <p className="mt-3 font-semibold text-yellow-400">
                YOU ASSUME ALL RISK FOR YOUR USE OF THE SERVICE AND GENERATED CONTENT.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">12. Limitation of Liability</h2>
            <div className="bg-slate-800/50 border-2 border-slate-700 p-4 rounded-lg">
              <p className="mb-3 font-bold text-white uppercase">
                TO THE MAXIMUM EXTENT PERMITTED BY LAW, PROMPT & PROTOCOL LLC, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AND
                AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS
                OF PROFITS, REVENUE, DATA, OR USE, ARISING OUT OF OR RELATED TO YOUR USE OF THE SERVICE, WHETHER BASED ON WARRANTY,
                CONTRACT, TORT (INCLUDING NEGLIGENCE), OR ANY OTHER LEGAL THEORY.
              </p>
              <p className="mb-3">This includes but is not limited to damages arising from:</p>
              <ul className="list-disc list-inside space-y-2 ml-4 text-sm">
                <li>Errors, mistakes, or inaccuracies in Generated Content</li>
                <li>Loss of data, including generated images after the 30-day retention period</li>
                <li>Unauthorized access to or alteration of your account or data</li>
                <li>Third-party service interruptions or failures (fal.ai, Google Gemini, PayPal)</li>
                <li>Infringement claims related to Generated Content</li>
                <li>Account suspension or termination</li>
              </ul>
              <p className="mt-3 font-bold">
                OUR TOTAL LIABILITY TO YOU FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THE SERVICE SHALL NOT EXCEED THE AMOUNT
                YOU PAID TO US IN THE 12 MONTHS PRECEDING THE CLAIM, OR $100 USD, WHICHEVER IS GREATER.
              </p>
              <p className="mt-3 text-xs text-slate-400">
                Some jurisdictions do not allow limitation of liability for incidental or consequential damages, so these limitations
                may not apply to you.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">13. Indemnification</h2>
            <p className="mb-4">
              You agree to indemnify, defend, and hold harmless Prompt & Protocol LLC, its affiliates, and their respective officers,
              directors, employees, and agents from and against any claims, liabilities, damages, losses, costs, and expenses
              (including reasonable attorneys' fees) arising out of or relating to:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Your use of the Service or Generated Content</li>
              <li>Your violation of these Terms or applicable laws</li>
              <li>Your infringement of any third-party rights, including intellectual property, privacy, or publicity rights</li>
              <li>Your Content or any content you submit to the Service</li>
              <li>Your violation of third-party provider terms (fal.ai, Google Gemini)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">14. Account Suspension and Termination</h2>
            <p className="mb-4">
              We reserve the right to suspend or terminate your account and access to the Service at any time, with or without notice, for:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Violation of these Terms or our Acceptable Use Policy</li>
              <li>Fraudulent activity, payment disputes, or chargebacks</li>
              <li>Non-payment of fees within 10 days of the due date</li>
              <li>Court orders, legal requirements, or law enforcement requests</li>
              <li>Security incidents or suspicious activity</li>
              <li>Interference with the normal operation of the Service</li>
              <li>Excessive or abusive usage patterns</li>
              <li>Any conduct we deem harmful to our service, other users, or third parties</li>
            </ul>
            <p className="mt-4 font-semibold text-yellow-400">
              Upon termination, your right to use the Service immediately ceases, and any unused tickets or subscription benefits
              will be forfeited without refund.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">15. Dispute Resolution and Arbitration</h2>
            <p className="mb-4">
              Any dispute arising out of or relating to these Terms or the Service shall be resolved through binding arbitration
              in accordance with the rules of the American Arbitration Association. The arbitration shall take place in the
              State of Florida, United States.
            </p>
            <p className="mb-4">
              <strong>Class Action Waiver:</strong> You agree to resolve disputes on an individual basis only and waive any right
              to participate in class action lawsuits or class-wide arbitration.
            </p>
            <p className="mb-4">
              <strong>Opt-Out Right:</strong> You may opt out of arbitration by sending written notice to{' '}
              <a href="mailto:promptandprotocol@gmail.com" className="text-cyan-400 hover:underline">promptandprotocol@gmail.com</a>{' '}
              within 30 days of first accepting these Terms. Your opt-out notice must include your name, address, and a clear
              statement that you wish to opt out of arbitration.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">16. Governing Law</h2>
            <p className="mb-4">
              These Terms shall be governed by and construed in accordance with the laws of the State of Florida, United States,
              without regard to its conflict of law provisions. Any legal action or proceeding (if arbitration is opted out or
              unavailable) shall be brought exclusively in the courts of Florida.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">17. Changes to Terms</h2>
            <p className="mb-4">
              We may update these Terms from time to time. We may notify you of material changes by:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Posting the updated Terms on the Service with an updated "Last Updated" date</li>
              <li>Sending email notification to registered users (for material changes)</li>
              <li>Providing 30 days advance notice for changes affecting pricing or subscription terms</li>
            </ul>
            <p className="mt-4">
              Your continued use of the Service after changes take effect constitutes acceptance of the revised Terms.
              If you do not agree to the updated Terms, you must stop using the Service and may cancel your subscription.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">18. Severability</h2>
            <p className="mb-4">
              If any provision of these Terms is found to be invalid, illegal, or unenforceable, the remaining provisions shall
              continue in full force and effect to the maximum extent possible.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">19. Entire Agreement</h2>
            <p className="mb-4">
              These Terms, together with our <a href="/privacy" className="text-cyan-400 hover:underline">Privacy Policy</a> and{' '}
              <a href="/refund" className="text-cyan-400 hover:underline">Refund Policy</a>, constitute the entire agreement between you
              and Prompt &amp; Protocol LLC regarding the Service and supersede all prior agreements and understandings.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold mb-4 text-cyan-400">20. Contact Information</h2>
            <p className="mb-4">
              For questions about these Terms, please contact us at:{' '}
              <a href="mailto:promptandprotocol@gmail.com" className="text-cyan-400 hover:underline">
                promptandprotocol@gmail.com
              </a>
            </p>
            <p className="text-sm text-slate-400">
              Response time: We aim to respond within 3 business days. Support is provided in English only.
            </p>
          </section>

          <div className="mt-12 p-6 border-2 border-cyan-500/30 rounded-lg bg-slate-800/50">
            <p className="font-semibold mb-3 text-lg">By using AI Design Studio, you acknowledge that:</p>
            <ul className="list-disc list-inside space-y-2 ml-4 text-sm">
              <li>You have read, understood, and agree to be bound by these Terms of Service</li>
              <li>You are at least 18 years of age</li>
              <li>You will comply with all applicable laws and third-party provider terms (fal.ai, Google Gemini)</li>
              <li>You understand the limitations and risks of AI-generated content</li>
              <li>You understand that your data may be shared with third-party AI providers</li>
              <li>You accept the disclaimer of warranties and limitation of liability</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  )
}
