export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#050810] text-white p-6">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-6 text-transparent bg-clip-text bg-gradient-to-r from-cyan-400 to-fuchsia-500">
          Terms of Service
        </h1>
        
        <div className="space-y-6 text-slate-300">
          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">1. Acceptance of Terms</h2>
            <p className="mb-3">
              By accessing or using Multiverse Mouse ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you must not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">2. Service Description & AI Technology</h2>
            <p className="mb-3">
              Multiverse Mouse provides an interface for AI-powered image generation using third-party AI models accessed through <strong className="text-white">FAL.ai infrastructure</strong>. Our service currently offers multiple AI models:
            </p>
            <ul className="list-disc ml-6 space-y-2">
              <li><strong className="text-white">NanoBanana Cluster</strong> - Generates 2 images per use (powered by Google Gemini 2.5 Flash via FAL.ai)</li>
              <li><strong className="text-white">NanoBanana Pro</strong> - Premium quality generation (powered by Google Gemini 3 Pro via FAL.ai)</li>
              <li><strong className="text-white">SeeDream 4.5</strong> - High-quality generation (powered by ByteDance via FAL.ai)</li>
            </ul>
            <p className="mt-3">
              By using this Service, you acknowledge that:
            </p>
            <ul className="list-disc ml-6 space-y-2">
              <li>All outputs are generated by artificial intelligence and may be imperfect</li>
              <li>AI models may produce unexpected or unintended results</li>
              <li>Images may contain invisible digital watermarks or metadata identifying their AI origin</li>
              <li>Model availability and pricing are subject to change</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">3. Eligibility</h2>
            <p className="font-bold text-yellow-400 mb-3">
              You must be at least 18 years of age to purchase tickets or generate images on Multiverse Mouse. Our service is not directed at or intended for individuals under the age of 18.
            </p>
            <p>
              By using this Service, you represent and warrant that you are at least 18 years old and have the legal capacity to enter into this agreement.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">4. Ticket Purchases & Pricing</h2>
            <div className="space-y-3">
              <div>
                <h3 className="font-bold text-white mb-1">Pricing Structure</h3>
                <p className="mb-2">Ticket costs vary by model and quality settings:</p>
                <ul className="list-disc ml-6 space-y-1 text-sm">
                  <li><strong>NanoBanana Cluster:</strong> 1 ticket (generates 2 images)</li>
                  <li><strong>NanoBanana Pro (2K):</strong> 1 ticket per generation</li>
                  <li><strong>NanoBanana Pro (4K):</strong> 2 tickets per generation</li>
                  <li><strong>SeeDream 4.5 (2K/4K):</strong> 1 ticket per generation</li>
                </ul>
                <p className="mt-2 text-sm text-yellow-400">Pricing is subject to change with 30 days' notice.</p>
              </div>
              <div>
                <h3 className="font-bold text-white mb-1">Non-Refundable</h3>
                <p>All ticket purchases are <strong className="text-white">final and non-refundable</strong> once the transaction is completed via PayPal. This includes:</p>
                <ul className="list-disc ml-6 space-y-1 text-sm mt-1">
                  <li>Unsuccessful generations due to prohibited content</li>
                  <li>User dissatisfaction with AI-generated results</li>
                  <li>Technical issues with third-party AI providers</li>
                  <li>Account suspension or termination for violations</li>
                </ul>
              </div>
              <div>
                <h3 className="font-bold text-white mb-1">Ticket Expiration</h3>
                <p>Tickets currently do not expire, but we reserve the right to modify this policy with 30 days' written notice to registered users.</p>
              </div>
            </div>
          </section>

          <section className="border-2 border-red-500/30 bg-red-500/5 p-4 rounded-lg">
            <h2 className="text-2xl font-bold text-red-400 mb-3">5. Prohibited Use Policy</h2>
            <p className="mb-3 font-bold">Users are strictly prohibited from using our AI tools to generate:</p>
            <ul className="list-disc ml-6 space-y-2">
              <li><strong>Sexual content involving minors</strong> or any content depicting, sexualizing, or endangering children</li>
              <li><strong>Non-consensual sexual content</strong>, deepfakes, or intimate images of real people without consent</li>
              <li><strong>Hate speech, harassment, or discriminatory content</strong> based on race, religion, gender, sexual orientation, disability, or other protected characteristics</li>
              <li><strong>Violence, self-harm, or dangerous activities</strong> including instructions for creating weapons or illegal substances</li>
              <li><strong>Copyrighted characters, trademarks, or logos</strong> that you do not have legal rights to use</li>
              <li><strong>Impersonation or fraud</strong> including fake identification documents or misleading medical/legal content</li>
              <li><strong>Spam, malware, or phishing</strong> attempts</li>
            </ul>
            <p className="mt-3 font-bold text-red-400">
              ⚠️ Violation of these rules will result in immediate permanent account termination without refund of remaining tickets.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">6. Ownership, Copyright & Licensing</h2>
            <div className="space-y-3">
              <div>
                <h3 className="font-bold text-white mb-1">Your Rights</h3>
                <p>Subject to these Terms, you retain ownership of images you generate through our Service. We claim no ownership over your specific outputs.</p>
              </div>
              <div>
                <h3 className="font-bold text-white mb-1">Copyright Limitations</h3>
                <p className="mb-2">You acknowledge that:</p>
                <ul className="list-disc ml-6 space-y-1 text-sm">
                  <li>AI-generated images may have limited copyright protection under current U.S. law (as of 2026)</li>
                  <li>Fully automated AI outputs may not qualify for copyright without significant human modification</li>
                  <li>You are responsible for ensuring you have rights to any reference images or prompts you submit</li>
                  <li>We make no warranties regarding the copyrightability of AI-generated content</li>
                </ul>
              </div>
              <div>
                <h3 className="font-bold text-white mb-1">License to Us</h3>
                <p>By generating images, you grant us a limited, non-exclusive license to:</p>
                <ul className="list-disc ml-6 space-y-1 text-sm">
                  <li>Store and display your images for the duration of our 30-day retention period</li>
                  <li>Use anonymized prompts and usage data to improve our service (no images shared)</li>
                  <li>Display sample outputs in marketing materials (only with your explicit consent)</li>
                </ul>
              </div>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">7. Image Storage & Deletion</h2>
            <div className="bg-yellow-500/10 border border-yellow-500/30 p-4 rounded-lg mb-3">
              <p className="font-bold text-yellow-400 mb-2">⚠️ IMPORTANT: Download Responsibility</p>
              <p>You are <strong className="text-white">solely responsible</strong> for downloading and backing up your generated images. We provide temporary storage only.</p>
            </div>
            <ul className="list-disc ml-6 space-y-2">
              <li>Images are stored for <strong className="text-white">30 days maximum</strong> on secure cloud servers (Vercel Blob Storage)</li>
              <li>After 30 days, images are <strong className="text-white">permanently and automatically deleted</strong></li>
              <li>We do not offer image recovery services after deletion</li>
              <li>Storage duration may be reduced with notice during periods of high storage costs</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">8. Service Availability & Limitations</h2>
            <p className="mb-3">We strive to provide reliable service, but:</p>
            <ul className="list-disc ml-6 space-y-2">
              <li>Service availability is <strong className="text-white">not guaranteed</strong> and may be interrupted for maintenance or technical issues</li>
              <li>AI model providers (FAL.ai, Google, ByteDance) may experience downtime or degraded performance</li>
              <li>We reserve the right to modify, suspend, or discontinue any feature with 30 days' notice</li>
              <li>Generation times may vary based on server load and model complexity</li>
              <li>We may implement rate limits or usage caps to prevent abuse</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">9. Disclaimer of Warranties</h2>
            <div className="bg-slate-900/50 border border-slate-700 p-4 rounded-lg">
              <p className="mb-2 font-bold text-white">THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND.</p>
              <p className="text-sm mb-2">We disclaim all warranties, express or implied, including but not limited to:</p>
              <ul className="list-disc ml-6 space-y-1 text-sm">
                <li>Merchantability or fitness for a particular purpose</li>
                <li>Accuracy, reliability, or quality of AI-generated images</li>
                <li>Uninterrupted or error-free operation</li>
                <li>Security of data transmission or storage</li>
                <li>Compliance with your specific legal or commercial requirements</li>
              </ul>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">10. Limitation of Liability</h2>
            <div className="bg-slate-900/50 border border-slate-700 p-4 rounded-lg">
              <p className="mb-2 font-bold text-white">TO THE MAXIMUM EXTENT PERMITTED BY LAW:</p>
              <ul className="list-disc ml-6 space-y-1 text-sm">
                <li>We shall not be liable for any indirect, incidental, special, consequential, or punitive damages</li>
                <li>Our total liability shall not exceed the amount you paid for tickets in the 90 days preceding the claim</li>
                <li>You agree to indemnify us against claims arising from your use of the Service or violation of these Terms</li>
              </ul>
              <p className="mt-2 text-xs text-slate-400">Some jurisdictions do not allow limitation of liability, so these limitations may not apply to you.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">11. Account Termination</h2>
            <p className="mb-2">We may terminate or suspend your account immediately, without notice, for:</p>
            <ul className="list-disc ml-6 space-y-1">
              <li>Violation of these Terms or our prohibited use policy</li>
              <li>Fraudulent payment activity or chargebacks</li>
              <li>Excessive or abusive usage patterns</li>
              <li>Any conduct we deem harmful to our service or other users</li>
            </ul>
            <p className="mt-2 text-sm text-yellow-400">Upon termination, all remaining tickets are forfeited without refund.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">12. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Material changes will be communicated via email with 30 days' notice. Continued use after changes constitutes acceptance of updated Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">13. Governing Law & Disputes</h2>
            <p className="mb-2">
              These Terms are governed by the laws of the State of Florida, United States, without regard to conflict of law principles.
            </p>
            <p className="text-sm">
              Any disputes shall be resolved through binding arbitration in accordance with the American Arbitration Association rules, except that either party may seek injunctive relief in court for intellectual property or confidentiality breaches.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-cyan-400 mb-3">14. Contact & Support</h2>
            <p>
              For questions about these Terms, contact us at:{' '}
              <a href="mailto:DirtySecretAi@gmail.com" className="text-cyan-400 hover:underline">
                DirtySecretAi@gmail.com
              </a>
            </p>
            <p className="mt-2 text-sm text-slate-400">
              Response time: We aim to respond within 3 business days. Support is provided in English only.
            </p>
          </section>
        </div>

        <div className="mt-12 text-center border-t border-slate-800 pt-6">
          <p className="text-sm text-slate-500">Last updated: January 22, 2026</p>
          <p className="text-xs text-slate-600 mt-2">Version 2.0</p>
        </div>
      </div>
    </div>
  )
}
